crypto: Rename custom free() function to crypto_free()
Fixes conflict with built in C function:

crypto/xts.c:337:13: error: conflicting types for built-in function 'free'; expected 'void(void *)' [-Werror=builtin-declaration-mismatch]

Signed-off-by: Lunarixus <Nathanb644@hotmail.co.uk>